[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "ccd70bd59d0f5c1a8e3b4bd931c6fb58a7d51b45"
julia_version = "1.10.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "dcf23810ddde5932565bcca6628d3d3d10dba035d8f8fa357ce94012edb935a4"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "0b2f793cc2bccc11d87eda95c687570364b05704"
julia_version = "1.11.1"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "5ce1e4763f9ba3091b080b2f1fc0e783ea40b05d177f13026d14fc0ec8bd52c0"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "b548c8a3b3302e83dc3ac98ee80ae21d1942bf53"
julia_version = "1.12.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "8ae3e1e5d7f19307c5379086b7164d109a79c5457bc84907fc8468cf561c70b8"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "56de315e549b90823e2b91f4c12d1f5e59e91950"
julia_version = "1.13.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "cffd73a85ecdf3211b0f5a6344bf5da992c9329352b4eafb2c6a1d5eaa44c2e9"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "c54341915bd7ea3e844e39b942cf1f166aa1f65e"
julia_version = "1.14.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "119b8e5d07cae0d3ad7a49271a58730dc059ebc440aced9a62e4ad176b79dd83"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73f8595293df5bb6eda3b761a5551e9e725c38db"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "ed61221965f4ac7190f06c1df2baa4240bcda63bab2646edf60c602b235f1f1e"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ced7398b2f5ac8dff292e524fc4451e33bab7c04"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "0b12ec74f13dbbf6a15f62f35a040f3872bddabc887fff9d93411e026537ea0f"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b9655b35fd2cb1f853659655bd60e360af3c7b0"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "7047b9fe6b74c37e4f6942672f20c30f82f2a99495bddd84578918ebad4986d1"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89d7fd2517899ad9a6e1935a91906ec7fa621d00"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "96ec3b4bda166f9c3e73d7ab92d955f19adf0aedafb03310a6e790e81b636934"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92b0021ee727729935888978e10b6ba47229e1f6"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "f0959de5d5aa34e84311fdd9755c0bf238a245164b5159cb4d5688708a837687"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.aarch64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "830f9b69180e998455f6c83daaccd936e7de4f65"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "7760ef1e1034eb4655e9fd861a41d2db65da9e0af62fcbce1554cad5b4f744c7"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8561195740f53fc08c0d89733309397c5d041c11"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "8ef843e50f24b68434ff127f6783220e61467e126d02b6f02829cb94ad2df963"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45f73b040708603f312bc03fd44862f428b710ba"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "5e232d07346c0bc25fc56fcbdc6dee13c0e2726a3a1b05b0e3f002f3ea6eed43"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e64540b813dc9b96106f8553df127e705bfaffaa"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "42271d60a27e411c02f93e95f219676a5fc23c5ede114a719a0bfc2d19b11f4f"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c74de1f7fef8e44d9593440d587d9e3a6cd6460"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "8d4994d106470aa9eec8fe957f7016f3ee227c273664e7d44f691428b6f0faf8"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.powerpc64le-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "c2445f8b1bbcb1e8c387263f01c5962e2b84b563"
julia_version = "1.10.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "f475ef530241ad89c393700d9b9115a694d1e6e962401662be83ca8e22ba4ed4"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "8550deef3b69da8efdc348a5dceab98b4ff3cbb5"
julia_version = "1.11.1"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "c0c1116e47d40ec786224bdbad4930ea5879be52a2987699d7ec2045419e3afb"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "d0fc4b8249dce0d66874a7132566da49a2fec5b1"
julia_version = "1.12.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "e806f3363b57f0da74496594bee27396eb5325468c5b8f464eb332e34470eebc"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "e15e97fd03634ad2438293576f84476d980cda52"
julia_version = "1.13.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "3ead9769b2fa348423356ebb89ac42459c8689e99b2a9ff3d342c794bf2f8384"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "41a2df09af4abad4d26ad0d4e824d252e2924ecb"
julia_version = "1.14.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "3754efc3e3ea7e5050a301ac77c28cad91456dfab010a59017cbbfb99188d20e"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb089712a6c3e6a0f086feffaaf90506ca02df4a"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "7322c2d1085628258ac122a0fea1566054738379346f288b1b8c3f6d1bd12bf8"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2cc30a7b890b949d2af9dd8764af4dc241bad10"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "4f5235f26884594fc837d04394d04e24f01c43a64101524c8666b5629a646211"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e261b3b75374c4902d4111bb6f86543f8302356"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "e505281d7fac9e730668183b78ee87336dfd875f9b595f228e188919e8b3b484"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c72436f620c423ad7024d7e43ba1b19c5f1bc1ce"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "f2ccb705c3e16351dbe43d354c3c6f199921db4f05d571ad4ffee2583824df5f"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "addd6025e57e12315a63c3473a6b64561e6a3033"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "b86a2b0e5bf3cd8d1dd1fcc684c2b73bb2df9a364882f3ccd2955373b2adcf3a"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9e2f0b32c36c834598fc4e951fda79c585092c5"
julia_version = "1.10.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "447802de90d9a8a16ed666f21cd497aeca21c79b0324518d31a28f24a1674921"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d305acef16334b06b6f1bb5083cea13a61f8ce6a"
julia_version = "1.11.1"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "23327fef916762e530cccd467c753da76153d94fdbe7e18132a5bde959b8a72b"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4728cb12f531e4c8eb7f41f2947071504b536c21"
julia_version = "1.12.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "226ef2a74edddf123c5d645ae77b0d04a4f0f2ae8df6ad8ca8117de47e89218d"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdfa5a62b48e1a928512bb4b704c5e8d256136f"
julia_version = "1.13.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "00cdd7534b0c2bde228acbd9cda5700637be5d11236164da51c6bd13b2008632"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdfa5a62b48e1a928512bb4b704c5e8d256136f"
julia_version = "1.14.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "00cdd7534b0c2bde228acbd9cda5700637be5d11236164da51c6bd13b2008632"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.3.1+0/Geant4_julia.v0.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
